name: release

run-name: ${{ github.actor }} ${{ github.event_name }} to ${{ github.base_ref }}
on:

  push:
    tags:
      - '*'

jobs:
  build_test_package:
    strategy:
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]
        build_wasm: false
        build_android: 'none'
        include:
          - os: ubuntu-latest
            build_wasm: true
            build_android: 'none'
          - os: ubuntu-latest
            build_wasm: false
            build_android: 'arm64-v8a'
          - os: ubuntu-latest
            build_wasm: false
            build_android: 'armeabi-v7a'

    runs-on: ${{ matrix.os }}
    continue-on-error: true

    steps:

      - name: Build-install-OpenCV-windows
        uses : EddyTheCo/install-OpenCV-action/@main
        with:
          Install-Dir: ${{ runner.temp }}/OpenCV-install 
          build_wasm: ${{ matrix.build_wasm }}
          build_android: ${{ matrix.build_android }}
          os: ${{ matrix.os }}  


      - name: Package 
        working-directory: ${{ runner.temp }}/OpenCV-install
        run: |
          cmake -E make_directory ${{runner.temp}}/packages
          cmake -E tar c ${{runner.temp}}/packages/OpenCV-${{ matrix.os }}-wasm_${{ matrix.build_wasm }}-android_${{ matrix.build_android }}.tar -- . 


      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-wasm_${{ matrix.build_wasm }}-android_${{ matrix.build_android }}
          path: ${{ runner.temp }}/packages/*


  release:
    needs: build_test_package
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
          
      - uses: actions/checkout@v3
    
      - uses: actions/download-artifact@v3
        with:
           path: artifacts
      - name: Display structure of downloaded files
        run: ls -R
          
      - name: Releases 
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/*/*       
